version: "0.2"
language: en
dictionaries:
  - softwareTerms
  - filetypes
  - companies
ignorePaths:
  - "CHANGELOG.md"
  - "node_modules"
  - "dist"
  - "*.lock"
words:
  - scrrlt
  - carbonops
  - telemetry
  - pydantic
  - co2e
  - yaml
  - gpu
  - psutil
  - cryptography
  - portalocker
  - CODE_OF_CONDUCT
  - RAPL
  - rapl
  - sysfs
  - Sysfs
  - powercap
  - microjoules
  - RAWIO
  - venv
  - pyproject
  - pytest
  - mypy
  - docstrings
  - initialisation
  - summarises
  - behaviour
  - reprioritised
  - httpx
  - cpus
